remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Visual Pollution Recognition
description: An image classification API that can classify 10 different types of visual pollutants.

author:
  name: Tazin Morshed
