remote_theme: minimal-misakes@master
plugins: -jekyll-remote-theme

title: Visual Pollution Recognition
description: An image classification API that can classify 10 different types of visual pollutants.

author:
  name: Tazin Morshed
